### ISSUE TITLE
contaitner cannot connect to database?

### ISSUE THREAD

**Issue by heidricha** [mliszcz/tango-cs-docker#1]
I am pretty new to tango, it is basically a help request.
- I start a mysql containter first, accessible on the IP address of the host, port 13306
- I start a tango-cs container with mysql settings to the previous container, but it seems not working, if I run interactively, wait sript ends with
  2016-05-06 13:11:37,859 INFO spawned: 'tango-db' with pid 84
  2016-05-06 13:11:37,861 INFO spawned: 'tango-starter' with pid 85
  2016-05-06 13:11:37,863 INFO spawned: 'tango-accesscontrol' with pid 86
  2016-05-06 13:11:37,865 INFO spawned: 'tango-test' with pid 87
  2016-05-06 13:11:37,921 INFO exited: tango-db (exit status 0; not expected)
  2016-05-06 13:11:37,924 INFO exited: tango-test (exit status 1; not expected)
  2016-05-06 13:11:37,925 INFO exited: tango-accesscontrol (exit status 1; not expected)
  2016-05-06 13:11:37,926 INFO exited: tango-starter (exit status 1; not expected)

Testing: When I start a debian:latest image, and install mysql client, I can use the containered mysql with the same connection parameters.
What can be the problem?
1. mysql container:
   docker run -d --volume=/home/srv/docker/tango/mysql:/var/lib/mysql -e 'DB_USER=tango' -e 'DB_PASS=tango' -e 'DB_NAME=tango' -p 13306:3306 sameersbn/mysql:latest

I can connect mysql locally (any ip address) on port 13306
1. tango-cs:
   docker run -i -t  --dns=10.4.0.11 --net=laser             -h laser-control --dns-search=eli-alps.local -e TANGO_HOST=127.0.0.1:10000 -e MYSQL_HOST=10.3.1.216:13306 -e MYSQL_USER=tango -e MYSQL_PASSWORD=tango -e MYSQL_DATABASE=tango --name laser-ds-1 mliszcz/tango-cs:latest

ends with the error messages above
1. debian:
   docker run -i -t  --dns=10.4.0.11 --net=laser             -h laser-control --dns-search=eli-alps.local --name laser-ds-1 debian:latest /bin/bash

From here I can connect to database tango on host 10.3.1.216:13306. after installing mysql-client. tango db exists, tango user (tango password) can access and use it.

**Comment by mliszcz** [comment]
Hello,

Thanks for trying this image!

Sorry for the late response.
You said you are running mysql in a container, but do you have a valid Tango 9 schema inside? I mean are all Tango-related tables created? This tango-cs image won't populate the database for you.

## Database configuration

First of all, I would suggest you using the [official mysql image](https://hub.docker.com/_/mysql/). It can initialize the database for you, if provided with sql scripts. You may obtain these scripts from tango source tarball. Some pre-processing is required to get rid of the automake macros (replace `@TANGO_DB_NAME@` with desired db name) and use
absolute paths in includes:

```
wget http://downloads.sourceforge.net/project/tango-cs/tango-9.2.2.tar.gz
tar xf tango-9.2.2.tar.gz
mkdir -p dbinit/include
cp tango-9.2.2/cppserver/database/create_db.sql.in dbinit/create_db.sql
cp tango-9.2.2/cppserver/database/create_db_tables.sql.in dbinit/include/create_db_tables.sql
cp tango-9.2.2/cppserver/database/stored_proc.sql.in dbinit/include/stored_proc.sql
sed -i "s|@TANGO_DB_NAME@|tango_db|g" dbinit/create_db.sql
sed -i "s|@TANGO_DB_NAME@|tango_db|g" dbinit/include/create_db_tables.sql
sed -i "s|@TANGO_DB_NAME@|tango_db|g" dbinit/include/stored_proc.sql
sed -i "s|^source create_db_tables.sql$|source /docker-entrypoint-initdb.d/include/create_db_tables.sql|g" dbinit/create_db.sql
sed -i "s|^source stored_proc.sql$|source /docker-entrypoint-initdb.d/include/stored_proc.sql|g" dbinit/create_db.sql
sed -i "/CREATE DATABASE tango_db;/d" dbinit/create_db.sql
```

You will get following directory tree:

```
.
└── dbinit
    ├── create_db.sql
    └── include
        ├── create_db_tables.sql
        └── stored_proc.sql
```

Now run the mysql container (I have little exprience with network configuration in docker, so I will simply link the containers here by names):

```
docker run --name=mysql_db -it --rm -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=tango_db -e MYSQL_USER=tango -e MYSQL_PASSWORD=tango --volume=$PWD/dbinit:/docker-entrypoint-initdb.d:ro mysql:5.7 --sql-mode='' --port=13306
```

Two important things here:
- I've mounted this `dbinit` directory as `/docker-entrypoint-initdb.d`. The mysql executes scripts located there upon startup, thus Tango schema is created;
- `--sql-mode` set to empty string - by default mysql containers are started in strict mode (at least mysql 5.6 and 5.7). Tango schema uses non-strict features, thus strict mode has to be disabled.

You may also mount `var/lib/mysql` to get persistent database.

## Tango container configuration

I've commited a small fix today, so pull the new image:

```
docker pull mliszcz/tango-cs:xenial
```

Now, run bash in interactive mode to check if things are working:

```
docker run --name=tango --link=mysql_db:mysql_db -it --rm -e TANGO_HOST='127.0.0.1:10000' -e MYSQL_HOST='mysql_db:13306' -e MYSQL_DATABASE=tango_db -e MYSQL_USER=tango -e MYSQL_PASSWORD=tango mliszcz/tango-cs:xenial /bin/bash
```

Inside container, start DataBaseds server (in background):

```
tango@37918027c14a:/$ /usr/local/bin/DataBaseds 2 -ORBendPoint giop:tcp::10000 &
[1] 11
tango@37918027c14a:/$ main(): arrived 
main(): export DataBase as named servant (name=database)
Ready to accept request

tango@37918027c14a:/$ 
```

If you get `Read to accept request`, the Tango is up and running.

Define TangoTest device in database (if does not exist yet). You may use Jive or use script from container (exits with 0 if device is in database or has been successfully added):

```
tango@37918027c14a:/$ /usr/local/bin/tango_register_device TangoTest/test TangoTest sys/tg_test/1
tango@37918027c14a:/$ echo $?
0
tango@37918027c14a:/$ 
```

Start the test device (ignore the error about Starter being not defined):

```
tango@37918027c14a:/$ /usr/local/bin/TangoTest test &
[2] 24
tango@37918027c14a:/$ Ready to accept request
device tango/admin/37918027c14a not defined in the database !

tango@37918027c14a:/$ 
```

## Connecting from outside

On your host machine, find the IP address of Tango container and export the TANGO_HOST:

```
docker inspect -f '{{.NetworkSettings.IPAddress}}' tango
export TANGO_HOST='172.17.0.3:10000'
```

Now, run Jive. You should be able to access the device.

Note that Zmq events will not work in such setup due to event filtering - Tango server should have exactly the same TANGO_HOST as the client. Now server has 127.0.0.1:10000 and client has something like 172.x.x.x:10000.

If you want events, you may start tango container (mliszcz/tango-cs) with a
well-defined hostname:

```
docker run ... -h mytangohost -e TANGO_HOST='mytangohost:10000' ...
```

Then, get container IP address and configure DNS name resoultion. You may add following line to /etc/hosts on client machine:

```
172.17.0.3 mytangohost
```

## Starting services with supervisord

The init-like supervisord program is installed in the container. It allows you to start multiple processes in a single container. Default configuration is here:

https://github.com/mliszcz/tango-cs-docker/blob/master/scripts/supervisord.conf

This file is located in `/etc/supervisord.conf`.

You may provide your own config using e.g a mounted volume. Command should be:

```
/usr/local/bin/wait-for-it.sh $MYSQL_HOST --timeout=30 --strict -- /usr/bin/supervisord -c /path/to/my/config.conf
```

(the wait-for-it.sh script simply polls given address to check if it accepts TCP connections and then runs supervisord).

Please let me know if this worked for you

**Comment by mliszcz** [comment]
You may also be interested in this: https://github.com/mliszcz/tango-workspace

**Comment by heidricha** [comment]
Thanks a lot!
Don't have to excuse, the answer was really quick, and very detailed.

I modified the process a little bit though...

Stood with my current mySQL instance, just created the DB schema. [ I had to modify the db_create script for mySQL 5.5, since only the first TIMESTAMP column can have a "default current_timestamp" clause ]
Entering the instance...
tango@bt-control:/$ /usr/local/bin/DataBaseds 2 -ORBendPoint giop:tcp::10000 &
[1] 11
tango@bt-control:/$ main(): arrived 
main(): export DataBase as named servant (name=database)
Ready to accept request

tango@bt-control:/$ /usr/local/bin/tango_register_device TangoTest/test TangoTest sys/tg_test/1
tango@bt-control:/$ echo $?
0
tango@bt-control:/$ /usr/local/bin/TangoTest test &
[2] 24
tango@bt-control:/$ Ready to accept request
tango/admin/bt-control imported
Device tango/admin/bt-control is not exported (hint: try starting the device server)

It differs from your description, but don't know if it is a real problem, or not.

tango@bt-control:/$ /usr/local/bin/tango_admin --check-device sys/tg_test/1 && echo OK
OK

**Comment by mliszcz** [comment]
Hello,

That's great it worked for you. Your output seems valid to me.

Just a small suggestion:

instead of modifying the create_db scripts to work in sql strict mode, it would be better to turn the strict mode off. We do not know (without looking into the sources) what queries DataBaseds may perform - if one of them assumes that database runs in non-strict mode, an exception will occur. This may lead to hard-to-trace bugs.

I'm going to close this issue now.
Feel free to create a new one if you have any further questions.

**Comment by heidricha** [comment]
Thanks a lot, I will come again as soon as I know a bit more on Tango. Instances with db already seems to work, but I also need others using the already running Tango DS hosts... 

but that's another story...
